version: '3'
services:
    postgres:
        restart: always
        env_file:
          - ./.env
        image: postgres
        container_name: postgres
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
        environment:  
          - POSTGRES_INITDB_ARGS="-A md5"   
          - POSTGRES_USER=${DATABASE_USER}
          - POSTGRES_PASSWORD=${DATABASE_PASS}  
        network_mode: host

